repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        exclude: (^migrations/|^venv/)

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language_version: python
        exclude: (^migrations/|^venv/)
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        language_version: python
        exclude: (^migrations/|^venv/)
